// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://kwpsfiqzosijmyjzabaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3cHNmaXF6b3Npam15anphYmFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTYzNjgsImV4cCI6MjA3NzQ3MjM2OH0.CKHFzBcot1tWX4UUxjzG5qRFM5gtNBask10HrXBkLa0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);